version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    image: wordpress
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mel-kouc/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mel-kouc/data/mariadb'
networks:
  inception:
    driver: bridge